### ISSUE TITLE
Failed to open TCP connection to qiniu-storage.pgyer.com:80

### ISSUE THREAD

**Issue by huFly** [shishirui/fastlane-plugin-pgyer#11]
服务器挂了吗？前两天还可以。。
报错信息：
Traceback (most recent call last):
        44: from /usr/local/bin/fastlane:23:in `<main>'
        43: from /usr/local/bin/fastlane:23:in `load'
        42: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
        41: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        40: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        39: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
        38: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        37: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        36: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        35: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        34: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        33: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        32: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        31: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        30: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        29: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        28: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        27: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        26: from Fastfile:36:in `block (2 levels) in parsing_binding'
        25: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        24: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        23: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        22: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        21: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
        20: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        19: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
        18: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-plugin-pgyer-0.2.2/lib/fastlane/plugin/pgyer/actions/pgyer_action.rb:66:in `run'
        17: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/connection.rb:175:in `post'
        16: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/connection.rb:387:in `run_request'
        15: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:143:in `build_response'
        14: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/request/multipart.rb:15:in `call'
        13: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/request/url_encoded.rb:15:in `call'
        12: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
        11: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:38:in `call'
        10: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
         9: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:43:in `block in call'
         8: from /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:87:in `perform_request'
         7: from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/net/http.rb:1455:in `request'
         6: from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/net/http.rb:909:in `start'
         5: from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
         4: from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/net/http.rb:935:in `connect'
         3: from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
         2: from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
         1: from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': [!] Failed to open TCP connection to qiniu-storage.pgyer.com:80 (getaddrinfo: nodename nor servname provided, or not known) (Faraday::ConnectionFailed)

**Comment by shishirui** [comment]
请升级到新版本
