### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by yangwang888** [shishirui/fastlane-plugin-pgyer#12]
![image](https://user-images.githubusercontent.com/64360617/90606944-1f074100-e233-11ea-9e0d-ec1377a6de91.png)
Is it possible to set the timeout retransmission or breakpoint retransmission function? Why does the 80s time out?

**Comment by shishirui** [comment]
网络问题，请升级到新版本即可，新版本支持网络加速功能
