### ISSUE TITLE
gitaction问题

### ISSUE THREAD

**Issue by lyf571321556** [shishirui/fastlane-plugin-pgyer#13]
在gitaction构建完成，回传到蒲公英的还是一直卡在上传那一步，会导致整个build process hang。

**Comment by lyf571321556** [comment]
猜测是因为国外线路回国的情况引发

**Comment by jiangxiaoqiang** [comment]
解决了嘛？

**Comment by shishirui** [comment]
可以试试这个
https://github.com/PGYER/pgyer-upload-app-action
@jiangxiaoqiang
