### ISSUE TITLE
新版本github actions上传超时

### ISSUE THREAD

**Issue by jiangxiaoqiang** [shishirui/fastlane-plugin-pgyer#19]
https://stackoverflow.com/questions/73503920/buffering-rb205in-sysread-nonblock-operation-timed-out-errnoetimedout

**Comment by shishirui** [comment]
可以试试：https://github.com/PGYER/pgyer-upload-app-action

**Comment by jicheng1014** [comment]
这个超时好像是因为国内互联互通的问题

**Comment by jicheng1014** [comment]
@jiangxiaoqiang  已在新版（0.2.4）支持 oversea 参数   不填写的话  会通过 ip 自动判断是否启用海外加速
