### ISSUE TITLE
Xcode10.1  fastlane 可以打包ipa   但是加入pgyer(api_key: "7f15xxxxxxxxxxxxxxxxxx141", user_key: "4a5bcxxxxxxxxxxxxxxx3a9e")不仅上传不了而且还一直重复循环打包,不加pgyer这个上传指令的话，上面的gym执行是没有问题的，正常且运行一次打包正常，我在fir上这样做没有问题，上传到fir的服务器可以安装正常运行

### ISSUE THREAD

**Issue by ZZImagine** [shishirui/fastlane-plugin-pgyer#7]

**Comment by zlovegsy** [comment]
desc "Push a new beta build to pgyer"
  lane :pgyer do
   
  
    gym(
    	
  		clean:true, #打包前clean项目
      export_options: { method: "ad-hoc" },
  		# export_method: "ad-hoc", #导出方式
  		configuration: "Release",#环境
  		output_directory:"./pgyer",#ipa的存放目录
  		output_name:get_build_number(),#输出ipa的文件名为当前的build号
  		workspace: "Lazy.xcworkspace",
  		scheme: "Lazy",
		  # export_xcargs: "-allowProvisioningUpdates",
	   
    )
   
   	pgyer(api_key: "", user_key: "", update_description: "update by fastlane")
  end

  desc "Push a new beta build to fir"
  lane :fir do

  	
    gym(

   		 # export_options: { method: "ad-hoc" },
   		 clean:true, #打包前clean项目
  		 export_method: "ad-hoc", #导出方式
   		 configuration: "Release",#环境
    	 output_directory:"./fir",#ipa的存放目录
   		 output_name:get_build_number(),#输出ipa的文件名为当前的build号
   		 workspace: "Lazy.xcworkspace",
   		 scheme: "Lazy",
   		 # export_xcargs: "-allowProvisioningUpdates",
     
    )
    firim(firim_api_token: '')

**Comment by cgs3238** [comment]
It’s because the lane name is duplicated with pyger action name.

Change the “pgyer” in this line to others, then issue will be gone:

lane :pgyer do

**Comment by shishirui** [comment]
请升级到新版本
