### ISSUE TITLE
Look here,Update Fastfile

### ISSUE THREAD

**Issue by Vanson** [shishirui/fastlane-plugin-pgyer#8]
If you do not set the installation type and installation password, you will get an error.
Please your Fastfile, add install_type: "2",password:"1234" parameters.

**Comment by JeffXue** [comment]
install_type:2 mean using the password to download?
how about the other type?

**Comment by IDEAL-YANG** [comment]
Pgyer update API from 1.0 to 2.0. 
(Required)Type of Install, this value is (2,3), 2:Password, 3:Restrict.
@JeffXue
